<?php


/**
 * Build a single script that can be run to install a mysql product index
 * with trigger updated eventSummary table, into an existing database.
 * 
 * Includes:
 *    - mysql_feplus/point_in_polygon.sql
 *    - mysql_feplus/feplus.sql
 *    - mysql_feplus/fedump.csv
 *    - productIndexSchemaMysql.sql
 *    - productIndexOnEventUpdateMysql.sql
 * 
 * Usage:
 *    create mysql database
 *    run this script and save output into sql file
 *    execute created script while connected to database
 * 
 * Jeremy Fee <jmfee@usgs.gov>
 * 2012-12-04
 */


echo "-- AUTOGENERATED, change with caution \n";
echo "-- generated by " . get_current_user() . "@" . gethostname() . " at " . @date("r") . "\n";
echo "-- script source was : " . __FILE__ . "\n";



$basedir = ""; //"/Users/jmfee/Documents/workspace/PDLtrunk/etc/schema/";

# run from current directory
chdir(dirname(__FILE__));


function run_query($query) {
	echo $query . ";\n";
	return true;
}



echo "\n\n-- ##### point_in_polygon.sql\n\n";
echo file_get_contents($basedir . 'mysql_feplus/point_in_polygon.sql');

echo "\n\n-- ##### feplus.sql\n\n";
echo file_get_contents($basedir . 'mysql_feplus/feplus.sql');


echo "\n\n-- ##### fedump.csv\n\n";


// make shape column hold text values
run_query("alter table feplus modify column shape TEXT");


// generate sql from data
$contents = file_get_contents($basedir . 'mysql_feplus/fedump.csv');
$lines = split("\n", $contents);
foreach ($lines as $line) {
	if ($line != '') {
		run_query("insert into feplus (s, m, e, h, l, area, shape, feregion, priority, dataset) values (" . $line . ")") or print mysql_error();
	}
}



// now convert text values to polygons
run_query("alter table feplus ADD COLUMN polyshape POLYGON AFTER shape") or print mysql_error();
run_query("update feplus SET polyshape = GeomFromText(shape)") or print mysql_error();
run_query("alter table feplus DROP COLUMN shape") or print mysql_error();
run_query("alter table feplus CHANGE polyshape shape POLYGON NOT NULL") or print mysql_error();
run_query("alter table feplus ADD SPATIAL INDEX(shape)") or print mysql_error();




echo "\n\n-- #### productIndexSchemaMysql.sql\n\n";
echo file_get_contents($basedir . 'productIndexSchemaMysql.sql');


#echo "\n\n-- #### productIndexOnEventUpdateMysql.sql\n\n";
#echo file_get_contents($basedir . 'productIndexOnEventUpdateMysql.sql');

