package gov.usgs.earthquake.indexer;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Map;

import org.junit.Assert;
import org.junit.Test;

import gov.usgs.earthquake.product.ProductId;

/**
 * This test reproduces a preferred origin selection bug, that led to the
 * indexer setting magnitude to null (by choosing a product without magnitude).
 * 
 * Jira issue EQH-2777.
 * Test data generated by etc/test_products/generate_test_products.php
 */
public class NullMagnitudeTest {

	public NullMagnitudeTest() {
	}

	@Test
	public void ci15508265() {
		Event event = new Event();
		ProductSummary summary;
		Map<String, String> properties;
		summary = new ProductSummary();
		summary.setIndexId(4460161L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:cap:ci15508265:1401809210580"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(6L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4499651L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:cap:ci15508265:1401835851770"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(6L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4451431L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:dyfi:ci15508265:1401791228475"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(new Date(1401788488000L));
		summary.setEventLatitude(new BigDecimal("32.6611667"));
		summary.setEventLongitude(new BigDecimal("-115.7041667"));
		summary.setEventDepth(new BigDecimal("8.93"));
		summary.setEventMagnitude(new BigDecimal("2.2"));
		summary.setVersion(null);
		summary.setPreferredWeight(51L);
		properties = summary.getProperties();
		properties.put("depth", "8.93");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("eventtime", "2014-06-03T09:41:28.000Z");
		properties.put("latitude", "32.6611667");
		properties.put("longitude", "-115.7041667");
		properties.put("magnitude", "2.2");
		properties.put("maxmmi", "2.0");
		properties.put("num-responses", "1");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4460121L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:dyfi:ci15508265:1401809305990"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(new Date(1401788488000L));
		summary.setEventLatitude(new BigDecimal("32.6611667"));
		summary.setEventLongitude(new BigDecimal("-115.7041667"));
		summary.setEventDepth(new BigDecimal("8.93"));
		summary.setEventMagnitude(new BigDecimal("2.2"));
		summary.setVersion(null);
		summary.setPreferredWeight(51L);
		properties = summary.getProperties();
		properties.put("depth", "8.93");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("eventtime", "2014-06-03T09:41:28.000Z");
		properties.put("latitude", "32.6611667");
		properties.put("longitude", "-115.7041667");
		properties.put("magnitude", "2.2");
		properties.put("maxmmi", "2.0");
		properties.put("num-responses", "1");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4499221L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:dyfi:ci15508265:1401835937350"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(new Date(1401788488000L));
		summary.setEventLatitude(new BigDecimal("32.6611667"));
		summary.setEventLongitude(new BigDecimal("-115.7125"));
		summary.setEventDepth(new BigDecimal("9.19"));
		summary.setEventMagnitude(new BigDecimal("2.2"));
		summary.setVersion(null);
		summary.setPreferredWeight(51L);
		properties = summary.getProperties();
		properties.put("depth", "9.19");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("eventtime", "2014-06-03T09:41:28.000Z");
		properties.put("latitude", "32.6611667");
		properties.put("longitude", "-115.7125");
		properties.put("magnitude", "2.2");
		properties.put("maxmmi", "2.0");
		properties.put("num-responses", "1");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4498991L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:focal-mechanism:ci15508265_fm1:1401835878640"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(6L);
		properties = summary.getProperties();
		properties.put("evaluation-status", "rejected");
		properties
				.put("eventParametersPublicID",
						"quakeml:www.data.scec.org/ws/event/query?eventid=15508265/140183587864");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("original-eventsource", "ci");
		properties.put("original-eventsourcecode", "15508265");
		properties.put("quakeml-publicid",
				"quakeml:www.data.scec.org/ws/event/query?Mecid=3077069");
		properties.put("review-status", "automatic");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4450281L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:focal-mechanism:ci15508265_fm1:1401789113330"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(new Date(1401788488730L));
		summary.setEventLatitude(new BigDecimal("32.6611667"));
		summary.setEventLongitude(new BigDecimal("-115.7041667"));
		summary.setEventDepth(new BigDecimal("8930"));
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(156L);
		properties = summary.getProperties();
		properties.put("beachball-source", "CI");
		properties.put("depth", "8930");
		properties.put("evaluation-status", "preliminary");
		properties
				.put("eventParametersPublicID",
						"quakeml:www.data.scec.org/ws/event/query?eventid=15508265/140178911333");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("eventtime", "2014-06-03T09:41:28.730Z");
		properties.put("latitude", "32.6611667");
		properties.put("longitude", "-115.7041667");
		properties.put("nodal-plane-1-dip", "81.0");
		properties.put("nodal-plane-1-rake", "-151.0");
		properties.put("nodal-plane-1-strike", "177.0");
		properties.put("nodal-plane-2-dip", "61.0");
		properties.put("nodal-plane-2-rake", "-10.0");
		properties.put("nodal-plane-2-strike", "82.0");
		properties.put("num-stations-used", "0");
		properties.put("original-eventsource", "ci");
		properties.put("original-eventsourcecode", "15508265");
		properties.put("quakeml-publicid",
				"quakeml:www.data.scec.org/ws/event/query?Mecid=3077069");
		properties.put("review-status", "automatic");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4499021L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:focal-mechanism:ci15508265_fm1:1401835882500"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(new Date(1401788488710L));
		summary.setEventLatitude(new BigDecimal("32.6611667"));
		summary.setEventLongitude(new BigDecimal("-115.7125"));
		summary.setEventDepth(new BigDecimal("9190"));
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(156L);
		properties = summary.getProperties();
		properties.put("beachball-source", "CI");
		properties.put("depth", "9190");
		properties.put("evaluation-status", "preliminary");
		properties
				.put("eventParametersPublicID",
						"quakeml:www.data.scec.org/ws/event/query?eventid=15508265/140183588250");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("eventtime", "2014-06-03T09:41:28.710Z");
		properties.put("latitude", "32.6611667");
		properties.put("longitude", "-115.7125");
		properties.put("nodal-plane-1-dip", "88.0");
		properties.put("nodal-plane-1-rake", "-172.0");
		properties.put("nodal-plane-1-strike", "173.0");
		properties.put("nodal-plane-2-dip", "82.0");
		properties.put("nodal-plane-2-rake", "-2.0");
		properties.put("nodal-plane-2-strike", "83.0");
		properties.put("num-stations-used", "0");
		properties.put("original-eventsource", "ci");
		properties.put("original-eventsourcecode", "15508265");
		properties.put("quakeml-publicid",
				"quakeml:www.data.scec.org/ws/event/query?Mecid=3077237");
		properties.put("review-status", "automatic");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4449881L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:general-link:ci15508265-0:1401788617646"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text",
				"Additional earthquake information for United States");
		properties
				.put("url",
						"http://earthquake.usgs.gov/earthquakes/world/index.php?regionID=24");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4449891L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:general-link:ci15508265-1:1401788617646"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text",
				"Additional earthquake information for California");
		properties
				.put("url",
						"http://earthquake.usgs.gov/earthquakes/states/index.php?regionID=5");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4449901L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:general-link:ci15508265-2:1401788617646"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text", "Additional earthquake information for Mexico");
		properties
				.put("url",
						"http://earthquake.usgs.gov/earthquakes/world/index.php?regionID=3");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4449981L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:general-link:ci15508265-0:1401788731140"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text",
				"Additional earthquake information for United States");
		properties
				.put("url",
						"http://earthquake.usgs.gov/earthquakes/world/index.php?regionID=24");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4449991L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:general-link:ci15508265-1:1401788731140"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text",
				"Additional earthquake information for California");
		properties
				.put("url",
						"http://earthquake.usgs.gov/earthquakes/states/index.php?regionID=5");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4450001L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:general-link:ci15508265-2:1401788731140"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text", "Additional earthquake information for Mexico");
		properties
				.put("url",
						"http://earthquake.usgs.gov/earthquakes/world/index.php?regionID=3");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4460041L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:general-link:ci15508265-0:1401809210580"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text",
				"Additional earthquake information for United States");
		properties
				.put("url",
						"http://earthquake.usgs.gov/earthquakes/world/index.php?regionID=24");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4460061L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:general-link:ci15508265-1:1401809210580"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text",
				"Additional earthquake information for California");
		properties
				.put("url",
						"http://earthquake.usgs.gov/earthquakes/states/index.php?regionID=5");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4460071L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:general-link:ci15508265-2:1401809210580"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text", "Additional earthquake information for Mexico");
		properties
				.put("url",
						"http://earthquake.usgs.gov/earthquakes/world/index.php?regionID=3");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4498911L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:general-link:ci15508265-0:1401835851770"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text",
				"Additional earthquake information for United States");
		properties
				.put("url",
						"http://earthquake.usgs.gov/earthquakes/world/index.php?regionID=24");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4498931L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:general-link:ci15508265-1:1401835851770"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text",
				"Additional earthquake information for California");
		properties
				.put("url",
						"http://earthquake.usgs.gov/earthquakes/states/index.php?regionID=5");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4449921L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:geoserve:ci15508265:1401788617646"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("country", "United States");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("location", "15km NW of Progreso, Mexico");
		properties.put("state", "California");
		properties.put("tsunamiFlag", "false");
		properties.put("utcOffset", "-420");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4450031L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:geoserve:ci15508265:1401788731140"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("country", "United States");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("location", "14km NW of Progreso, Mexico");
		properties.put("state", "California");
		properties.put("tsunamiFlag", "false");
		properties.put("utcOffset", "-420");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4460091L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:geoserve:ci15508265:1401809210580"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("country", "United States");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("location", "14km NW of Progreso, Mexico");
		properties.put("state", "California");
		properties.put("tsunamiFlag", "false");
		properties.put("utcOffset", "-420");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4498951L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:geoserve:ci15508265:1401835851770"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("country", "United States");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("location", "14km S of Seeley, California");
		properties.put("state", "California");
		properties.put("tsunamiFlag", "false");
		properties.put("utcOffset", "-420");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4449911L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:nearby-cities:ci15508265:1401788617646"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4450021L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:nearby-cities:ci15508265:1401788731140"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4460081L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:nearby-cities:ci15508265:1401809210580"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4498941L);
		summary.setId(ProductId
				.parse("urn:usgs-product:us:nearby-cities:ci15508265:1401835851770"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion(null);
		summary.setPreferredWeight(1L);
		properties = summary.getProperties();
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4449861L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:origin:ci15508265:1401788617646"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(new Date(1401788488800L));
		summary.setEventLatitude(new BigDecimal("32.6588"));
		summary.setEventLongitude(new BigDecimal("-115.7173"));
		summary.setEventDepth(new BigDecimal("9.9"));
		summary.setEventMagnitude(new BigDecimal("2.3"));
		summary.setVersion("2");
		summary.setPreferredWeight(156L);
		properties = summary.getProperties();
		properties.put("azimuthal-gap", "133.2");
		properties.put("cube-location-method", "B");
		properties.put("cube-magnitude-type", "L");
		properties.put("depth", "9.9");
		properties.put("eids-feeder", "atlantic.gps.caltech.edu");
		properties.put("eids-feeder-sequence", "4133");
		properties.put("event-type", "earthquake");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("eventtime", "2014-06-03T09:41:28.800Z");
		properties.put("horizontal-error", "0.5");
		properties.put("latitude", "32.6588");
		properties.put("location-method-algorithm", "B");
		properties.put("location-method-class", "Unknown");
		properties.put("longitude", "-115.7173");
		properties.put("magnitude", "2.3");
		properties.put("magnitude-error", "0.2");
		properties.put("magnitude-num-stations-used", "39");
		properties.put("magnitude-type", "Ml");
		properties.put("minimum-distance", "0.09881468");
		properties.put("num-phases-used", "27");
		properties.put("num-stations-used", "24");
		properties.put("review-status", "AUTOMATIC");
		properties.put("standard-error", "0.38");
		properties.put("version", "2");
		properties.put("vertical-error", "1.0");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4449971L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:origin:ci15508265:1401788731140"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(new Date(1401788488730L));
		summary.setEventLatitude(new BigDecimal("32.6611667"));
		summary.setEventLongitude(new BigDecimal("-115.7041667"));
		summary.setEventDepth(new BigDecimal("8.93"));
		summary.setEventMagnitude(new BigDecimal("2.22"));
		summary.setVersion("3");
		summary.setPreferredWeight(156L);
		properties = summary.getProperties();
		properties.put("azimuthal-gap", "136");
		properties.put("depth", "8.93");
		properties.put("depth-type", "FROM_LOCATION");
		properties.put("evaluation-status", "preliminary");
		properties.put("event-type", "earthquake");
		properties
				.put("eventParametersPublicID",
						"quakeml:www.data.scec.org/ws/event/query?eventid=15508265/140178873114");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("eventtime", "2014-06-03T09:41:28.730Z");
		properties.put("latitude", "32.6611667");
		properties.put("longitude", "-115.7041667");
		properties.put("magnitude", "2.22");
		properties.put("magnitude-azimuthal-gap", "71.7");
		properties.put("magnitude-error", "0.138");
		properties.put("magnitude-num-stations-used", "48");
		properties.put("magnitude-source", "CI");
		properties.put("magnitude-type", "ml");
		properties.put("minimum-distance", "0.1003");
		properties.put("num-phases-used", "29");
		properties.put("num-stations-used", "19");
		properties.put("origin-source", "CI");
		properties.put("quakeml-publicid",
				"quakeml:www.data.scec.org/ws/event/query?Eventid=15508265");
		properties.put("review-status", "automatic");
		properties.put("standard-error", "0.28");
		properties.put("version", "3");
		properties.put("vertical-error", "0.98");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4460031L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:origin:ci15508265:1401809210580"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(new Date(1401788488730L));
		summary.setEventLatitude(new BigDecimal("32.6611667"));
		summary.setEventLongitude(new BigDecimal("-115.7041667"));
		summary.setEventDepth(new BigDecimal("8.93"));
		summary.setEventMagnitude(new BigDecimal("2.22"));
		summary.setVersion("5");
		summary.setPreferredWeight(156L);
		properties = summary.getProperties();
		properties.put("azimuthal-gap", "136");
		properties.put("depth", "8.93");
		properties.put("depth-type", "FROM_LOCATION");
		properties.put("evaluation-status", "reviewed");
		properties.put("event-type", "earthquake");
		properties
				.put("eventParametersPublicID",
						"quakeml:www.data.scec.org/ws/event/query?eventid=15508265/140180921058");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("eventtime", "2014-06-03T09:41:28.730Z");
		properties.put("latitude", "32.6611667");
		properties.put("longitude", "-115.7041667");
		properties.put("magnitude", "2.22");
		properties.put("magnitude-azimuthal-gap", "71.7");
		properties.put("magnitude-error", "0.138");
		properties.put("magnitude-num-stations-used", "48");
		properties.put("magnitude-source", "CI");
		properties.put("magnitude-type", "ml");
		properties.put("minimum-distance", "0.1003");
		properties.put("num-phases-used", "29");
		properties.put("num-stations-used", "19");
		properties.put("origin-source", "CI");
		properties.put("quakeml-publicid",
				"quakeml:www.data.scec.org/ws/event/query?Eventid=15508265");
		properties.put("review-status", "reviewed");
		properties.put("standard-error", "0.28");
		properties.put("version", "5");
		properties.put("vertical-error", "0.98");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4498901L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:origin:ci15508265:1401835851770"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(new Date(1401788488710L));
		summary.setEventLatitude(new BigDecimal("32.6611667"));
		summary.setEventLongitude(new BigDecimal("-115.7125"));
		summary.setEventDepth(new BigDecimal("9.19"));
		summary.setEventMagnitude(new BigDecimal("2.22"));
		summary.setVersion("7");
		summary.setPreferredWeight(156L);
		properties = summary.getProperties();
		properties.put("azimuthal-gap", "131");
		properties.put("depth", "9.19");
		properties.put("depth-type", "FROM_LOCATION");
		properties.put("evaluation-status", "final");
		properties.put("event-type", "earthquake");
		properties
				.put("eventParametersPublicID",
						"quakeml:www.data.scec.org/ws/event/query?eventid=15508265/140183585177");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("eventtime", "2014-06-03T09:41:28.710Z");
		properties.put("horizontal-error", "0.34");
		properties.put("latitude", "32.6611667");
		properties.put("longitude", "-115.7125");
		properties.put("magnitude", "2.22");
		properties.put("magnitude-azimuthal-gap", "71.7");
		properties.put("magnitude-error", "0.144");
		properties.put("magnitude-num-stations-used", "45");
		properties.put("magnitude-source", "CI");
		properties.put("magnitude-type", "ml");
		properties.put("minimum-distance", "0.01663");
		properties.put("num-phases-used", "43");
		properties.put("num-stations-used", "29");
		properties.put("origin-source", "CI");
		properties.put("quakeml-publicid",
				"quakeml:www.data.scec.org/ws/event/query?Eventid=15508265");
		properties.put("review-status", "reviewed");
		properties.put("standard-error", "0.22");
		properties.put("version", "7");
		properties.put("vertical-error", "0.42");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4449931L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:phase-data:ci15508265:1401788621600"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(new Date(1401788488860L));
		summary.setEventLatitude(new BigDecimal("32.6588326"));
		summary.setEventLongitude(new BigDecimal("-115.7173309"));
		summary.setEventDepth(new BigDecimal("9.9"));
		summary.setEventMagnitude(new BigDecimal("2.31"));
		summary.setVersion("2");
		summary.setPreferredWeight(156L);
		properties = summary.getProperties();
		properties.put("azimuthal-gap", "134");
		properties.put("depth", "9.9");
		properties.put("depth-type", "FROM_LOCATION");
		properties.put("evaluation-status", "preliminary");
		properties.put("event-type", "earthquake");
		properties
				.put("eventParametersPublicID",
						"quakeml:www.data.scec.org/ws/event/query?eventid=15508265/140178862160");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("eventtime", "2014-06-03T09:41:28.860Z");
		properties.put("horizontal-error", "0.51");
		properties.put("latitude", "32.6588326");
		properties.put("longitude", "-115.7173309");
		properties.put("magnitude", "2.31");
		properties.put("magnitude-azimuthal-gap", "72.4");
		properties.put("magnitude-error", "0.206");
		properties.put("magnitude-num-stations-used", "39");
		properties.put("magnitude-source", "CI");
		properties.put("magnitude-type", "ml");
		properties.put("minimum-distance", "0.1006");
		properties.put("num-phases-used", "27");
		properties.put("num-stations-used", "24");
		properties.put("origin-source", "CI");
		properties.put("quakeml-publicid",
				"quakeml:www.data.scec.org/ws/event/query?Eventid=15508265");
		properties.put("review-status", "automatic");
		properties.put("standard-error", "0.38");
		properties.put("version", "2");
		properties.put("vertical-error", "0.98");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4450011L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:phase-data:ci15508265:1401788731140"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(new Date(1401788488730L));
		summary.setEventLatitude(new BigDecimal("32.6611667"));
		summary.setEventLongitude(new BigDecimal("-115.7041667"));
		summary.setEventDepth(new BigDecimal("8.93"));
		summary.setEventMagnitude(new BigDecimal("2.22"));
		summary.setVersion("3");
		summary.setPreferredWeight(156L);
		properties = summary.getProperties();
		properties.put("azimuthal-gap", "136");
		properties.put("depth", "8.93");
		properties.put("depth-type", "FROM_LOCATION");
		properties.put("evaluation-status", "preliminary");
		properties.put("event-type", "earthquake");
		properties
				.put("eventParametersPublicID",
						"quakeml:www.data.scec.org/ws/event/query?eventid=15508265/140178873114");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("eventtime", "2014-06-03T09:41:28.730Z");
		properties.put("latitude", "32.6611667");
		properties.put("longitude", "-115.7041667");
		properties.put("magnitude", "2.22");
		properties.put("magnitude-azimuthal-gap", "71.7");
		properties.put("magnitude-error", "0.138");
		properties.put("magnitude-num-stations-used", "48");
		properties.put("magnitude-source", "CI");
		properties.put("magnitude-type", "ml");
		properties.put("minimum-distance", "0.1003");
		properties.put("num-phases-used", "29");
		properties.put("num-stations-used", "19");
		properties.put("origin-source", "CI");
		properties.put("quakeml-publicid",
				"quakeml:www.data.scec.org/ws/event/query?Eventid=15508265");
		properties.put("review-status", "automatic");
		properties.put("standard-error", "0.28");
		properties.put("version", "3");
		properties.put("vertical-error", "0.98");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4460051L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:phase-data:ci15508265:1401809210580"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(new Date(1401788488730L));
		summary.setEventLatitude(new BigDecimal("32.6611667"));
		summary.setEventLongitude(new BigDecimal("-115.7041667"));
		summary.setEventDepth(new BigDecimal("8.93"));
		summary.setEventMagnitude(new BigDecimal("2.22"));
		summary.setVersion("5");
		summary.setPreferredWeight(156L);
		properties = summary.getProperties();
		properties.put("azimuthal-gap", "136");
		properties.put("depth", "8.93");
		properties.put("depth-type", "FROM_LOCATION");
		properties.put("evaluation-status", "reviewed");
		properties.put("event-type", "earthquake");
		properties
				.put("eventParametersPublicID",
						"quakeml:www.data.scec.org/ws/event/query?eventid=15508265/140180921058");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("eventtime", "2014-06-03T09:41:28.730Z");
		properties.put("latitude", "32.6611667");
		properties.put("longitude", "-115.7041667");
		properties.put("magnitude", "2.22");
		properties.put("magnitude-azimuthal-gap", "71.7");
		properties.put("magnitude-error", "0.138");
		properties.put("magnitude-num-stations-used", "48");
		properties.put("magnitude-source", "CI");
		properties.put("magnitude-type", "ml");
		properties.put("minimum-distance", "0.1003");
		properties.put("num-phases-used", "29");
		properties.put("num-stations-used", "19");
		properties.put("origin-source", "CI");
		properties.put("quakeml-publicid",
				"quakeml:www.data.scec.org/ws/event/query?Eventid=15508265");
		properties.put("review-status", "reviewed");
		properties.put("standard-error", "0.28");
		properties.put("version", "5");
		properties.put("vertical-error", "0.98");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4498921L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:phase-data:ci15508265:1401835851770"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(new Date(1401788488710L));
		summary.setEventLatitude(new BigDecimal("32.6611667"));
		summary.setEventLongitude(new BigDecimal("-115.7125"));
		summary.setEventDepth(new BigDecimal("9.19"));
		summary.setEventMagnitude(new BigDecimal("2.22"));
		summary.setVersion("7");
		summary.setPreferredWeight(156L);
		properties = summary.getProperties();
		properties.put("azimuthal-gap", "131");
		properties.put("depth", "9.19");
		properties.put("depth-type", "FROM_LOCATION");
		properties.put("evaluation-status", "final");
		properties.put("event-type", "earthquake");
		properties
				.put("eventParametersPublicID",
						"quakeml:www.data.scec.org/ws/event/query?eventid=15508265/140183585177");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("eventtime", "2014-06-03T09:41:28.710Z");
		properties.put("horizontal-error", "0.34");
		properties.put("latitude", "32.6611667");
		properties.put("longitude", "-115.7125");
		properties.put("magnitude", "2.22");
		properties.put("magnitude-azimuthal-gap", "71.7");
		properties.put("magnitude-error", "0.144");
		properties.put("magnitude-num-stations-used", "45");
		properties.put("magnitude-source", "CI");
		properties.put("magnitude-type", "ml");
		properties.put("minimum-distance", "0.01663");
		properties.put("num-phases-used", "43");
		properties.put("num-stations-used", "29");
		properties.put("origin-source", "CI");
		properties.put("quakeml-publicid",
				"quakeml:www.data.scec.org/ws/event/query?Eventid=15508265");
		properties.put("review-status", "reviewed");
		properties.put("standard-error", "0.22");
		properties.put("version", "7");
		properties.put("vertical-error", "0.42");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4449871L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:scitech-link:ci15508265-waveform_ci:1401788617652"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion("01");
		summary.setPreferredWeight(6L);
		properties = summary.getProperties();
		properties.put("addon-code", "Waveform_CI");
		properties.put("addon-type", "LinkURL");
		properties.put("eids-feeder", "atlantic.gps.caltech.edu");
		properties.put("eids-feeder-sequence", "4134");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text", "Waveforms");
		properties
				.put("url",
						"http://pasadena.wr.usgs.gov/eqview/cgi-bin/makePublicView.php?EVID=15508265");
		properties.put("version", "01");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4449941L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:scitech-link:ci15508265-waveform_ci:1401788628391"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion("01");
		summary.setPreferredWeight(6L);
		properties = summary.getProperties();
		properties.put("addon-code", "Waveform_CI");
		properties.put("addon-type", "LinkURL");
		properties.put("eids-feeder", "lhotse");
		properties.put("eids-feeder-sequence", "11593");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text", "Waveforms");
		properties
				.put("url",
						"http://pasadena.wr.usgs.gov/eqview/cgi-bin/makePublicView.php?EVID=15508265");
		properties.put("version", "01");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4449961L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:scitech-link:ci15508265-waveform_ci:1401788642614"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion("01");
		summary.setPreferredWeight(6L);
		properties = summary.getProperties();
		properties.put("addon-code", "Waveform_CI");
		properties.put("addon-type", "LinkURL");
		properties.put("eids-feeder", "manaslu.gps.caltech.edu");
		properties.put("eids-feeder-sequence", "9141");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text", "Waveforms");
		properties
				.put("url",
						"http://pasadena.wr.usgs.gov/eqview/cgi-bin/makePublicView.php?EVID=15508265");
		properties.put("version", "01");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4450261L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:scitech-link:ci15508265-focalmech_1:1401789112659"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion("01");
		summary.setPreferredWeight(6L);
		properties = summary.getProperties();
		properties.put("addon-code", "FocalMech_1");
		properties.put("addon-type", "LinkURL");
		properties.put("eids-feeder", "manaslu.gps.caltech.edu");
		properties.put("eids-feeder-sequence", "9142");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text", "SCSN First Motion Mechanism 1");
		properties
				.put("url",
						"http://pasadena.wr.usgs.gov/recenteqs/QuakeAddons/ci15508265.cifm1.html");
		properties.put("version", "01");
		event.addProduct(summary);
		summary = new ProductSummary();
		summary.setIndexId(4450271L);
		summary.setId(ProductId
				.parse("urn:usgs-product:ci:scitech-link:ci15508265-focalmech_1:1401789113468"));
		summary.setEventSource("ci");
		summary.setEventSourceCode("15508265");
		summary.setEventTime(null);
		summary.setEventLatitude(null);
		summary.setEventLongitude(null);
		summary.setEventDepth(null);
		summary.setEventMagnitude(null);
		summary.setVersion("01");
		summary.setPreferredWeight(6L);
		properties = summary.getProperties();
		properties.put("addon-code", "FocalMech_1");
		properties.put("addon-type", "LinkURL");
		properties.put("eids-feeder", "lhotse");
		properties.put("eids-feeder-sequence", "11594");
		properties.put("eventsource", "ci");
		properties.put("eventsourcecode", "15508265");
		properties.put("text", "SCSN First Motion Mechanism 1");
		properties
				.put("url",
						"http://pasadena.wr.usgs.gov/recenteqs/QuakeAddons/ci15508265.cifm1.html");
		properties.put("version", "01");
		event.addProduct(summary);

		Assert.assertFalse("Event is not deleted", event.isDeleted());
		Assert.assertNotNull("Event magnitude is not null", event
				.getMagnitude());
		Assert.assertEquals("Event magnitude is correct",
				new BigDecimal("2.22"), event.getMagnitude());
		ProductSummary preferredOrigin = event.getPreferredOriginProduct();
		Assert.assertEquals("selected correct preferred origin product",
				"urn:usgs-product:ci:origin:ci15508265:1401835851770",
				preferredOrigin.getId().toString());
	}
}